In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/Naliniakshaya/Main-project-Airline-passenger-dataset/main/Air%20line%20Data%20sets.csv"

df = pd.read_csv(url)

df.head()

,Passenger_ID,Passenger_Name,Age,Gender,Airline,Flight_Number,Flight_Type,Departure_Airport,Arrival_Airport,Departure_City,...,Arrival_Time,Seat_No,Class,Ticket_Price_USD,Baggage_Weight_KG,Status,Delay_Minutes,Booking_Channel,Meal_Preference,Loyalty_Points
0,PAX0001,Rahul Sharma,34,Male,IndiGo,AI513,National,MAA,DEL,Chennai,...,9.15,12A,Economy,145,18.5,On Time,0,Website,Veg,2200
1,PAX0002,Priya Nair,29,Female,Air India,AI512,International,BOM,DXB,Mumbai,...,14.45,2C,Business,860,24.0,Delayed,45,Mobile App,Non-Veg,8400
2,PAX0003,Arjun Mehta,41,Male,Emirates,EK220,International,DEL,LHR,Delhi,...,9.55,1A,First,2450,30.2,On Time,0,Travel Agent,Veg,13200
3,PAX0004,Sneha Iyer,25,Female,Qatar Airways,QR901,International,BLR,SIN,Bangalore,...,14.00,22B,Economy,420,15.6,Cancelled,0,Website,Vegan,3500
4,PAX0005,Vikram Rao,38,Male,Singapore Airlines,SQ318,International,HYD,JFK,Hyderabad,...,13.45,4D,Business,1980,27.5,On Time,0,Mobile App,Non-Veg,9700

In [ ]:
print("Dataset Shape:", df.shape)
print("\nColumn Names:")
print(df.columns.tolist())

Dataset Shape: (500, 23)

Column Names:
['Passenger_ID', 'Passenger_Name', 'Age', 'Gender', 'Airline', 'Flight_Number', 'Flight_Type', 'Departure_Airport', 'Arrival_Airport', 'Departure_City', 'Arrival_City', 'Travel_Date', 'Departure_Time', 'Arrival_Time', 'Seat_No', 'Class', 'Ticket_Price_USD', 'Baggage_Weight_KG', 'Status', 'Delay_Minutes', 'Booking_Channel', 'Meal_Preference', 'Loyalty_Points']

In [ ]:
df.head()

,Passenger_ID,Passenger_Name,Age,Gender,Airline,Flight_Number,Flight_Type,Departure_Airport,Arrival_Airport,Departure_City,...,Arrival_Time,Seat_No,Class,Ticket_Price_USD,Baggage_Weight_KG,Status,Delay_Minutes,Booking_Channel,Meal_Preference,Loyalty_Points
0,PAX0001,Rahul Sharma,34,Male,IndiGo,AI513,National,MAA,DEL,Chennai,...,9.15,12A,Economy,145,18.5,On Time,0,Website,Veg,2200
1,PAX0002,Priya Nair,29,Female,Air India,AI512,International,BOM,DXB,Mumbai,...,14.45,2C,Business,860,24.0,Delayed,45,Mobile App,Non-Veg,8400
2,PAX0003,Arjun Mehta,41,Male,Emirates,EK220,International,DEL,LHR,Delhi,...,9.55,1A,First,2450,30.2,On Time,0,Travel Agent,Veg,13200
3,PAX0004,Sneha Iyer,25,Female,Qatar Airways,QR901,International,BLR,SIN,Bangalore,...,14.00,22B,Economy,420,15.6,Cancelled,0,Website,Vegan,3500
4,PAX0005,Vikram Rao,38,Male,Singapore Airlines,SQ318,International,HYD,JFK,Hyderabad,...,13.45,4D,Business,1980,27.5,On Time,0,Mobile App,Non-Veg,9700

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Passenger_ID       500 non-null    object
 1   Passenger_Name     500 non-null    object
 2   Age                500 non-null    int64
 3   Gender             500 non-null    object
 4   Airline            500 non-null    object
 5   Flight_Number      500 non-null    object
 6   Flight_Type        500 non-null    object
 7   Departure_Airport  500 non-null    object
 8   Arrival_Airport    500 non-null    object
 9   Departure_City     500 non-null    object
 10  Arrival_City       500 non-null    object
 11  Travel_Date        500 non-null    object
 12  Departure_Time     500 non-null    float64
 13  Arrival_Time       500 non-null    float64
 14  Seat_No            500 non-null    object
 15  Class              500 non-null    object
 16  Ticket_Price_USD   500 non-null    int64
 17  Baggage_Weight_KG  500 non-null    float64
 18  Status             500 non-null    object
 19  Delay_Minutes      500 non-null    int64
 20  Booking_Channel    500 non-null    object
 21  Meal_Preference    500 non-null    object
 22  Loyalty_Points     500 non-null    int64
dtypes: float64(3), int64(4), object(16)
memory usage: 90.0+ KB

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 50

In [ ]:
for col in df.columns:
    print("\n", col)
    print(df[col].unique()[:10])

 Passenger_ID
['PAX0001' 'PAX0002' 'PAX0003' 'PAX0004' 'PAX0005' 'PAX0006' 'PAX0007'
 'PAX0008' 'PAX0009' 'PAX0010']

 Passenger_Name
['Rahul Sharma' 'Priya Nair' 'Arjun Mehta' 'Sneha Iyer' 'Vikram Rao'
 'Meera Kapoor' 'Karan Verma' 'Ananya Das' 'Rohit Menon' 'Divya Krishnan']

 Age
[34 29 41 25 38 31 45 27 36 30]

 Gender
['Male' 'Female']

 Airline
['IndiGo' 'Air India' 'Emirates' 'Qatar Airways' 'Singapore Airlines'
 'Lufthansa' 'British Airways' 'Delta']

 Flight_Number
['AI513' 'AI512' 'EK220' 'QR901' 'SQ318' 'LH760' 'BA256' 'DL404' '6E788'
 'AI662']

 Flight_Type
['National' 'International']

 Departure_Airport
['MAA' 'BOM' 'DEL' 'BLR' 'HYD' 'CCU']

 Arrival_Airport
['DEL' 'DXB' 'LHR' 'SIN' 'JFK' 'FRA' 'BLR' 'MAA' 'BOM' 'HYD']

 Departure_City
['Chennai' 'Mumbai' 'Delhi' 'Bangalore' 'Hyderabad' 'Kolkata']

 Arrival_City
['Delhi' 'Dubai' 'London' 'Singapore' 'New York' 'Frankfurt' 'Bangalore'
 'Chennai' 'Mumbai' 'Hyderabad']

 Travel_Date
['01-02-2025' '01-03-2025' '01-04-2025' '01-05-2025' '01-06-2025'
 '01-07-2025' '01-08-2025' '01-09-2025' '01-10-2025' '01-11-2025']

 Departure_Time
[ 6.3  11.    1.2   8.1  22.    3.45 10.15  5.5  14.25  9.4 ]

 Arrival_Time
[ 9.15 14.45  9.55 14.   13.45 11.2  18.3  17.2  17.1  12.25]

 Seat_No
['12A' '2C' '1A' '22B' '4D' '18F' '3A' '25C' '14D' '9B']

 Class
['Economy' 'Business' 'First' 'Premium Economy']

 Ticket_Price_USD
[ 145  860 2450  420 1980  980 1650  740  125  310]

 Baggage_Weight_KG
[18.5 24.  30.2 15.6 27.5 19.3 26.8 17.2 12.  20.5]

 Status
['On Time' 'Delayed' 'Cancelled']

 Delay_Minutes
[ 0 45 30 35 90 20 40 55 25 50]

 Booking_Channel
['Website' 'Mobile App' 'Travel Agent']

 Meal_Preference
['Veg' 'Non-Veg' 'Vegan' 'Jain']

 Loyalty_Points
[ 2200  8400 13200  3500  9700  5400 11000  4100  1800  6200]

In [9]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/Naliniakshaya/Main-project-Airline-passenger-dataset/main/Air%20line%20Data%20sets.csv"

df = pd.read_csv(url)

df.head()

,Passenger_ID,Passenger_Name,Age,Gender,Airline,Flight_Number,Flight_Type,Departure_Airport,Arrival_Airport,Departure_City,...,Arrival_Time,Seat_No,Class,Ticket_Price_USD,Baggage_Weight_KG,Status,Delay_Minutes,Booking_Channel,Meal_Preference,Loyalty_Points
0,PAX0001,Rahul Sharma,34,Male,IndiGo,AI513,National,MAA,DEL,Chennai,...,9.15,12A,Economy,145,18.5,On Time,0,Website,Veg,2200
1,PAX0002,Priya Nair,29,Female,Air India,AI512,International,BOM,DXB,Mumbai,...,14.45,2C,Business,860,24.0,Delayed,45,Mobile App,Non-Veg,8400
2,PAX0003,Arjun Mehta,41,Male,Emirates,EK220,International,DEL,LHR,Delhi,...,9.55,1A,First,2450,30.2,On Time,0,Travel Agent,Veg,13200
3,PAX0004,Sneha Iyer,25,Female,Qatar Airways,QR901,International,BLR,SIN,Bangalore,...,14.00,22B,Economy,420,15.6,Cancelled,0,Website,Vegan,3500
4,PAX0005,Vikram Rao,38,Male,Singapore Airlines,SQ318,International,HYD,JFK,Hyderabad,...,13.45,4D,Business,1980,27.5,On Time,0,Mobile App,Non-Veg,9700

In [11]:
df.isnull().sum()

Passenger_ID         0
Passenger_Name       0
Age                  0
Gender               0
Airline              0
Flight_Number        0
Flight_Type          0
Departure_Airport    0
Arrival_Airport      0
Departure_City       0
Arrival_City         0
Travel_Date          0
Departure_Time       0
Arrival_Time         0
Seat_No              0
Class                0
Ticket_Price_USD     0
Baggage_Weight_KG    0
Status               0
Delay_Minutes        0
Booking_Channel      0
Meal_Preference      0
Loyalty_Points       0
dtype: int64

In [12]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (450, 23)

In [18]:
print(df.columns.tolist())

['Passenger_ID', 'Passenger_Name', 'Age', 'Gender', 'Airline', 'Flight_Number', 'Flight_Type', 'Departure_Airport', 'Arrival_Airport', 'Departure_City', 'Arrival_City', 'Travel_Date', 'Departure_Time', 'Arrival_Time', 'Seat_No', 'Class', 'Ticket_Price_USD', 'Baggage_Weight_KG', 'Status', 'Delay_Minutes', 'Booking_Channel', 'Meal_Preference', 'Loyalty_Points']

In [24]:
print(df.columns)

Index(['Passenger_ID', 'Passenger_Name', 'Age', 'Gender', 'Airline',
       'Flight_Number', 'Flight_Type', 'Departure_Airport', 'Arrival_Airport',
       'Departure_City', 'Arrival_City', 'Travel_Date', 'Departure_Time',
       'Arrival_Time', 'Seat_No', 'Class', 'Ticket_Price_USD',
       'Baggage_Weight_KG', 'Status', 'Delay_Minutes', 'Booking_Channel',
       'Meal_Preference', 'Loyalty_Points'],
      dtype='object')

In [26]:
for i, col in enumerate(df.columns):
    print(i, repr(col))

0 'Passenger_ID'
1 'Passenger_Name'
2 'Age'
3 'Gender'
4 'Airline'
5 'Flight_Number'
6 'Flight_Type'
7 'Departure_Airport'
8 'Arrival_Airport'
9 'Departure_City'
10 'Arrival_City'
11 'Travel_Date'
12 'Departure_Time'
13 'Arrival_Time'
14 'Seat_No'
15 'Class'
16 'Ticket_Price_USD'
17 'Baggage_Weight_KG'
18 'Status'
19 'Delay_Minutes'
20 'Booking_Channel'
21 'Meal_Preference'
22 'Loyalty_Points'

In [28]:
# Check number of rows and columns
print("Shape:", df.shape)

Shape: (450, 23)

In [29]:
# Check missing values
print("Missing values:")
print(df.isnull().sum())

Missing values:
Passenger_ID         0
Passenger_Name       0
Age                  0
Gender               0
Airline              0
Flight_Number        0
Flight_Type          0
Departure_Airport    0
Arrival_Airport      0
Departure_City       0
Arrival_City         0
Travel_Date          0
Departure_Time       0
Arrival_Time         0
Seat_No              0
Class                0
Ticket_Price_USD     0
Baggage_Weight_KG    0
Status               0
Delay_Minutes        0
Booking_Channel      0
Meal_Preference      0
Loyalty_Points       0
dtype: int64

In [30]:
# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [31]:
# Check data types
print("\nData types:")
print(df.dtypes)

Data types:
Passenger_ID          object
Passenger_Name        object
Age                    int64
Gender                object
Airline               object
Flight_Number         object
Flight_Type           object
Departure_Airport     object
Arrival_Airport       object
Departure_City        object
Arrival_City          object
Travel_Date           object
Departure_Time       float64
Arrival_Time         float64
Seat_No               object
Class                 object
Ticket_Price_USD       int64
Baggage_Weight_KG    float64
Status                object
Delay_Minutes          int64
Booking_Channel       object
Meal_Preference       object
Loyalty_Points         int64
dtype: object

In [36]:
df = df.drop_duplicates()

In [37]:
print("Final shape:", df.shape)

Final shape: (450, 23)

In [38]:
# Check missing values
print("Missing Values:")
print(df.isnull().sum())

# Check duplicate records
print("\nDuplicate Records:", df.duplicated().sum())

# Remove duplicate records
df = df.drop_duplicates()

# Check final shape
print("\nDataset Shape After Cleaning:", df.shape)

Missing Values:
Passenger_ID         0
Passenger_Name       0
Age                  0
Gender               0
Airline              0
Flight_Number        0
Flight_Type          0
Departure_Airport    0
Arrival_Airport      0
Departure_City       0
Arrival_City         0
Travel_Date          0
Departure_Time       0
Arrival_Time         0
Seat_No              0
Class                0
Ticket_Price_USD     0
Baggage_Weight_KG    0
Status               0
Delay_Minutes        0
Booking_Channel      0
Meal_Preference      0
Loyalty_Points       0
dtype: int64

Duplicate Records: 0

Dataset Shape After Cleaning: (450, 23)

In [41]:
#Statistical Analysis
# Statistical summary
df.describe()

,Age,Departure_Time,Arrival_Time,Ticket_Price_USD,Baggage_Weight_KG,Delay_Minutes,Loyalty_Points
count,450.000000,450.000000,450.000000,450.000000,450.000000,450.000000,450.000000
mean,34.797778,10.242444,11.529000,949.677778,19.672222,10.444444,6674.666667
std,7.940844,7.191376,4.857412,767.991448,6.988260,21.029257,4353.661439
min,23.000000,1.100000,0.300000,95.000000,8.500000,0.000000,900.000000
25%,28.000000,4.250000,8.500000,160.000000,12.500000,0.000000,2700.000000
50%,33.000000,8.750000,11.400000,860.000000,19.300000,0.000000,5400.000000
75%,40.000000,16.000000,15.300000,1450.000000,26.500000,11.250000,9900.000000
max,52.000000,23.450000,18.500000,2800.000000,32.000000,90.000000,16000.000000

In [42]:
# Mean
df.mean(numeric_only=True)

Age                    34.797778
Departure_Time         10.242444
Arrival_Time           11.529000
Ticket_Price_USD      949.677778
Baggage_Weight_KG      19.672222
Delay_Minutes          10.444444
Loyalty_Points       6674.666667
dtype: float64

In [43]:
# Median
df.median(numeric_only=True)S

Age                    33.00
Departure_Time          8.75
Arrival_Time           11.40
Ticket_Price_USD      860.00
Baggage_Weight_KG      19.30
Delay_Minutes           0.00
Loyalty_Points       5400.00
dtype: float64

In [44]:
# Standard deviation
df.std(numeric_only=True)

Age                     7.940844
Departure_Time          7.191376
Arrival_Time            4.857412
Ticket_Price_USD      767.991448
Baggage_Weight_KG       6.988260
Delay_Minutes          21.029257
Loyalty_Points       4353.661439
dtype: float64

In [45]:
# Standard deviation
df.std(numeric_only=True)

Age                     7.940844
Departure_Time          7.191376
Arrival_Time            4.857412
Ticket_Price_USD      767.991448
Baggage_Weight_KG       6.988260
Delay_Minutes          21.029257
Loyalty_Points       4353.661439
dtype: float64